var grunt = require("grunt");

exports.manifest = {
  main: function(test) {
    test.expect(1);

    var expectA = "CACHE MANIFEST\n# This manifest was generated by grunt-contrib HTML5 Cache Manifest Generator\n\nCACHE:\ntest.js\ntest.css\nfolder_one/one.css\nfolder_one/one.js\nfolder_two/two.js\nfolder_two/two.css\n\nNETWORK:\n*\n";
    var resultA = grunt.file.read("fixtures/manifest/manifest.appcache");

    test.equal(expectA, resultA, "should generate a cache manifest");

    test.done();
  }
};